
services:
  # Context7 MCP Server
  context7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.context7
    container_name: mcp-context7
    stdin_open: true
    tty: true
    networks:
      - mcp-network
    restart: unless-stopped

  # Puppeteer MCP Server
  puppeteer:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.puppeteer
    container_name: mcp-puppeteer
    stdin_open: true
    tty: true
    networks:
      - mcp-network
    restart: unless-stopped
    # Puppeteer needs some additional capabilities
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    # Mount for downloads if needed
    volumes:
      - ./downloads:/home/mcpuser/downloads

  # PostgreSQL MCP Server
  postgres:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.postgres
    container_name: mcp-postgres
    stdin_open: true
    tty: true
    networks:
      - mcp-network
    restart: unless-stopped
    environment:
      - DATABASE_URL_STRING=${DATABASE_URL_STRING}

  # Sequential Thinking MCP Server
  sequentialthinking:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.sequentialthinking
    container_name: mcp-sequentialthinking
    stdin_open: true
    tty: true
    networks:
      - mcp-network
    restart: unless-stopped

  # MCP Gateway Server (Optional - for unified access)
  # Use: docker-compose --profile gateway up -d
  mcp-gateway:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gateway
    container_name: mcp-gateway
    ports:
      - "8812:8811"
    networks:
      - mcp-network
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    profiles:
      - gateway

networks:
  mcp-network:
    driver: bridge